# Site settings - in YAML this is a comment, btw. Two-space indentation for the array for Minima theme.
title: Donna's LXD portfolio
author:
  name: Donna MacLeod
  email: info@dmacleod.ca
description: "Learning Experience Design (LXD)"

# Build settings
remote_theme: jekyll/minima
# theme: theme-name - for local install
show_excerpts: true  # to show the first part of the blog?
minima:
  skin: dark
